# override 
services:
  rabbit-mq:
    image: rabbitmq:3.8-management
    container_name: campus-rabbitmq
    ports:
      - "5672:5672"     # app connection
      - "15672:15672"   # UI dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: campus-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: campus-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Chaitanya
      POSTGRES_PASSWORD: Chaitanya@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped 

  auth-service:
    build: ./services/auth-service
    ports:
      - "3000:3000"
    env_file:
    - ./services/auth-service/.env
    environment:  
      NODE_ENV: development
    volumes:
      - ./services/auth-service:/app   
      - /app/node_modules
    command: pnpm run dev 
    depends_on:
    #   - rabbit-mq
      # - redis
      - postgres
    restart: unless-stopped

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/User-service/.env  
    environment:
      NODE_ENV: development
    volumes:  
      - ./services/user-service:/app
      - /app/node_modules
    command : pnpm run dev   
    depends_on:
      # - rabbit-mq
      - postgres
    restart: unless-stopped  

    carpool-service :
      build: ./services/carpool-service
      ports:
        - "3002:3002"
      env_file:
        - ./services/carpool-service/.env
      environment:
        NODE_ENV: development 
      volumes:
        - ./services/carpool-service:/app
        - /app/node_modules
      command: pnpm run dev
      depends_on:
          - postgres
      restart: unless-stopped
    
volumes:
  postgres_data:

